CREATE DATABASE loja_web;
USE loja_web;

CREATE TABLE CLIENTE (
    CPF VARCHAR(11) NOT NULL,
    Nome_Completo VARCHAR(150) NOT NULL,
    Celular VARCHAR(15),
    Email VARCHAR(100) NOT NULL,
    Data_Nascimento DATE,
    PRIMARY KEY (CPF)
);

CREATE TABLE CATEGORIA (
    ID_Categoria INT AUTO_INCREMENT NOT NULL,
    Nome_Categoria VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_Categoria)
);

CREATE TABLE ENDERECO (
    ID_Endereco INT AUTO_INCREMENT NOT NULL,
    Logradouro VARCHAR(150) NOT NULL,
    Numero VARCHAR(10),
    Bairro VARCHAR(50),
    Cidade VARCHAR(50),
    CEP VARCHAR(8),
    CPF_Cliente VARCHAR(11) NOT NULL,
    PRIMARY KEY (ID_Endereco),
    FOREIGN KEY (CPF_Cliente) REFERENCES CLIENTE(CPF) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SUBCATEGORIA (
    ID_Subcategoria INT AUTO_INCREMENT NOT NULL,
    Nome_Subcategoria VARCHAR(50) NOT NULL,
    ID_Categoria INT NOT NULL,
    PRIMARY KEY (ID_Subcategoria),
    FOREIGN KEY (ID_Categoria) REFERENCES CATEGORIA(ID_Categoria)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE PRODUTO (
    ID_Produto INT AUTO_INCREMENT NOT NULL,
    Modelo VARCHAR(100) NOT NULL,
    Fabricante VARCHAR(100),
    Preco_Base DECIMAL(10,2) NOT NULL,
    Quantidade_Disponivel INT DEFAULT 0,
    ID_Subcategoria INT NOT NULL,
    PRIMARY KEY (ID_Produto),
    FOREIGN KEY (ID_Subcategoria) REFERENCES SUBCATEGORIA(ID_Subcategoria)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ITEM_SERIE (
    Numero_Serie VARCHAR(50) NOT NULL,
    ID_Produto INT NOT NULL,
    PRIMARY KEY (Numero_Serie),
    FOREIGN KEY (ID_Produto) REFERENCES PRODUTO(ID_Produto)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COMPRA (
    ID_Compra INT AUTO_INCREMENT NOT NULL,
    Data_Hora DATETIME DEFAULT CURRENT_TIMESTAMP,
    Desconto_Aplicado DECIMAL(10,2) DEFAULT 0.00,
    Forma_Pagamento VARCHAR(50) NOT NULL,
    Total_Compra DECIMAL(10,2) NOT NULL,
    CPF_Cliente VARCHAR(11) NOT NULL,
    ID_Endereco INT NOT NULL,
    PRIMARY KEY (ID_Compra),
    FOREIGN KEY (CPF_Cliente) REFERENCES CLIENTE(CPF)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_Endereco) REFERENCES ENDERECO(ID_Endereco)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ITEM_COMPRA (
    ID_Compra INT NOT NULL,
    ID_Produto INT NOT NULL,
    Quantidade INT NOT NULL,
    Preco_Praticado DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ID_Compra, ID_Produto),
    FOREIGN KEY (ID_Compra) REFERENCES COMPRA(ID_Compra)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_Produto) REFERENCES PRODUTO(ID_Produto)
        ON DELETE RESTRICT ON UPDATE CASCADE
);