version: '3.8'

services:
  back:
    build: ./backend
    container_name: back
    ports:
      - "4000:4000"

  front:
    build: ./frontend
    container_name: front
    ports:
      - "3000:3000"
    depends_on:
      - back